# Generated by Django 4.1.3 on 2022-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=10)),
                ('nama_material', models.CharField(max_length=255)),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('berat_kg', models.IntegerField()),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
