# Generated by Django 4.1.3 on 2022-12-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listmaterial', '0002_distributemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='berat_kg',
            field=models.FloatField(),
        ),
    ]
